# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12__VQ8QKGKgCt-8Kq8QMW0RuwOg7_oNS
"""

from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re
import nest_asyncio
nest_asyncio.apply()

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    if not isinstance(text, str):
        return ""

    text = re.sub(r"http\S+|www\S+|https\S+", '', text, flags=re.MULTILINE)
    text = re.sub(r'\@\w+|\#','', text)
    text = re.sub(r'[^A-Za-z\s]', '', text)
    text = text.lower()

    tokens = text.split()
    cleaned_tokens = [
        lemmatizer.lemmatize(word)
        for word in tokens
        if word not in stop_words
    ]
    return " ".join(cleaned_tokens)

model = joblib.load('sentiment_model.pkl')
vectorizer = joblib.load('tfidf_vectorizer.pkl')

app = FastAPI(title="Sentiment Analysis API", version="1.0")

class TweetRequest(BaseModel):
    tweet: str

@app.get("/")
def home():
    return {"message": "Welcome to the Sentiment Analysis API on Hugging Face!"}

@app.post("/predict")
def predict_sentiment(request: TweetRequest):
    cleaned = clean_text(request.tweet)
    vectorized = vectorizer.transform([cleaned])
    prediction = model.predict(vectorized)[0]
    sentiment_label = "Positive" if str(prediction) in ["1", "Positive", "4"] else "Negative"

    return {
        "original_tweet": request.tweet,
        "clean_tweet": cleaned,
        "sentiment": sentiment_label
    }