# -*- coding: utf-8 -*-
"""Twitter_Sentiment_Analysis_FsatAPIs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yTCuop-UOq4sUMQVjcWuPMZUt5Ns3ZKu

#  Twitter Sentiment Analysis: NLP Preprocessing & Machine Learning
This project covers end-to-end sentiment analysis on a tweet dataset, including data cleaning, NLP preprocessing (NLTK), text vectorization for tweet sentiment analysis using Python, Pandas, and NLTK and building a classification model using Logistic Regression (Scikit-Learn).
"""

import pandas  as pd
import numpy as np

# NLP Preproceesing
import nltk
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re # Regular expression

#convert text to vector
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import pandas as pd

df = pd.read_csv(
    '/content/training.1600000.processed.noemoticon.csv',
    encoding='latin-1',
    header=None,
    names=['target', 'ids', 'date', 'flag', 'user', 'text'],
    engine='python',
    on_bad_lines='skip'
)


df.head()

"""# Load data"""

df=df.sample(n=10000 ,random_state=24 )

"""# Exploration Data"""

df.head()

df.shape

df.columns

df.info()

df.isna().sum()

df.duplicated().sum()

"""we load the first 10,000 from data and we note there is no null or duplicated data but data need preprocessing to:


*  Make usable names to colums
*  drop the not importent coulms (Make fouces to target and tweet)

# Preprocessing Data
"""

# Make usable names to colums
columns_name=['target','id','date','flag','user','tweet']
df.columns=columns_name

df # to check

# drop the not importent coulms (Make fouces to target and tweet
df.drop(columns=['id','date','flag','user'],inplace=True)

df # to check

df['target'].value_counts()

"""# NLP(Text Preprocessing(tweet)"""

stopwords=set(stopwords.words('english'))
Lemmatazation=WordNetLemmatizer()

def NLP(tweet) :
  tweet = tweet.lower()               # make all latter in words lower
  tweet = re.sub(r'<.*>','',tweet)    # remove HTML Tages
  tweet = re.sub(r'http\S+','',tweet) # remove links
  tweet = re.sub(r'[^a-z]', ' ', tweet)  # remove any (tags,digits) just keep leeters


  # Tokenize the tweet to words
  words = word_tokenize(tweet)

  # Remove stopwords
  words = [word for word in words if word not in stopwords ]

  # Lemmatazation
  words =[ Lemmatazation.lemmatize(word) for word in words]

  # Join spliting words after cleaning
  tweet=' '.join(words)

  return tweet

df['clean_tweet']=df['tweet'].apply(NLP)

df

df=df.drop(columns=['tweet'])

df

# split data
x=df['clean_tweet']
y=df['target']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=24)

y_train.value_counts() # balance

"""## Convert text to numbers using TfidfVectorizer"""

tf_idf=TfidfVectorizer()
x_train=tf_idf.fit_transform(x_train)
x_test=tf_idf.transform(x_test)

"""# Modleing"""

model=LogisticRegression()
model.fit(x_train,y_train)
pred=model.predict(x_test)
acc=accuracy_score(y_test,pred)
print(f"Accuracy_score of LogisticRegression is :{acc}")

# check predection for the fisrt row
print(f"predection target {pred[0]} , actual target: {y_test.iloc[0]}")

"""# FastAPIs"""

import joblib

#   Vectorizer
joblib.dump(tf_idf, 'tfidf_vectorizer.pkl')

#   model
joblib.dump(model, 'sentiment_model.pkl')

print("  Vectorizer and model saved!")

!pip install fastapi uvicorn pyngrok nest-asyncio

from pyngrok import ngrok
ngrok.set_auth_token("3HlHspxMEqd7yvrkLRHgUDQUFYX_62bCCfgc4ZohFTQT6QqxA")

from fastapi import FastAPI
from pydantic import BaseModel
import nest_asyncio
from pyngrok import ngrok
import uvicorn
import joblib
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

ngrok.kill()


nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

vectorizer = joblib.load('tfidf_vectorizer.pkl')
model = joblib.load('sentiment_model.pkl')

app = FastAPI(title="Sentiment Analysis API", version="1.0")

class TweetRequest(BaseModel):
    tweet: str

def clean_text(text: str) -> str:
    text = text.lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'[^a-z]', ' ', text)
    words = word_tokenize(text)
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]
    return ' '.join(words)

@app.get("/")
def home():
    return {"message": "Hello to FastAPI with colab"}

@app.post("/predict")
def predict_sentiment(request: TweetRequest):

    cleaned = clean_text(request.tweet)

    vectorized_text = vectorizer.transform([cleaned])

    prediction = model.predict(vectorized_text)[0]


    sentiment = "Positive" if prediction == 4 else "Negative"

    return {
        "original_tweet": request.tweet,
        "clean_tweet": cleaned,
        "sentiment": sentiment
    }

nest_asyncio.apply()
public_url = ngrok.connect(8000)
print(f"Your url code: {public_url.public_url}")

# server
config = uvicorn.Config(app, host="127.0.0.1", port=8000, log_level="info")
server = uvicorn.Server(config)
await server.serve()https://blurb-autopilot-impaired.ngrok-free.dev/$0